import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "./components/Header";
import Hero from "./components/Hero";
import Hero2 from "./components/Hero2";
import Carousel1 from "./components/Carousel1";
import Carousel2 from "./components/Carousel2";
import Wholesale from "./components/Wholesale";
import RedLogos from "./components/RedLogos";
import Newsletter from "./components/Newsletter";
import Footer from "./components/Footer";

const Home: NextPage = () => {
  return (
    <div className="overflow-hidden">
      <Head>
        <title>Red Brick 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Hero2 />
      <Carousel1 />
      <Carousel2 />
      <Wholesale />
      <RedLogos />
      <Newsletter />
      <Footer />
    </div>
  );
};

export default Home;
